#ifndef COLORS_H
#define COLORS_H

#define SDL_WHITE (SDL_Color){255, 255, 255, SDL_ALPHA_OPAQUE}
#define SDL_RED (SDL_Color){255, 0, 0, SDL_ALPHA_OPAQUE}
#define SDL_GREEN (SDL_Color){0, 255, 0, SDL_ALPHA_OPAQUE}
#define SDL_BLUE (SDL_Color){0, 0, 255, SDL_ALPHA_OPAQUE}
#define SDL_CYAN (SDL_Color){0, 255, 255, SDL_ALPHA_OPAQUE}
#define SDL_YELLOW (SDL_Color){255, 255, 0, SDL_ALPHA_OPAQUE}
#define SDL_FUCHSIA (SDL_Color){255, 0, 255, SDL_ALPHA_OPAQUE}
#define SDL_LIGHT_GRAY (SDL_Color){160, 160, 160, SDL_ALPHA_OPAQUE}
#define SDL_GRAY (SDL_Color){128, 128, 128, SDL_ALPHA_OPAQUE}
#define SDL_DARK_GRAY (SDL_Color){64, 64, 64, SDL_ALPHA_OPAQUE}
#define SDL_BLACK (SDL_Color){0, 0, 0, SDL_ALPHA_OPAQUE}
#define SDL_TRANSPARENT (SDL_Color){0, 0, 0, SDL_ALPHA_TRANSPARENT}

#endif
